language: java

# Experimental group for MySQL 5.6
group: dev

jdk:
  - oraclejdk8

env:
  - DB=mysql
  - DB=h2
  - DB=postgres

cache:
  directories:
    - $HOME/.m2

before_install:
  # Extra Chrome setup from: http://stackoverflow.com/questions/19255976
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install karma && npm install karma-jasmine karma-chrome-launcher
  - cd ui && npm install -g grunt-cli bower
  - npm install
  - bower install
  - grunt build && cd ..

script:
  - mvn test -P $DB
  - "mvn compile findbugs:check"
  - cd ui && grunt test
